# Generated by Django 5.0 on 2024-01-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0009_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bookspdf'),
        ),
    ]
